if not E2Helper then return end

E2Helper.Descriptions["isTIV(e:)"] = "Returns 1 if entity is a supported Tornado Intercept Vehicle, 0 otherwise."
E2Helper.Descriptions["tivState(e:)"] = "Returns the deployment state of the TIV (idle, stabilizing, lowering, deploying_spikes, anchored, retracting, raising, lofted)."
E2Helper.Descriptions["tivIsDeployed(e:)"] = "Returns 1 if the TIV is fully deployed and anchored, 0 otherwise."
E2Helper.Descriptions["tivIsAnchored(e:)"] = "Returns 1 if the TIV is anchored, 0 otherwise."
E2Helper.Descriptions["tivIsTransitioning(e:)"] = "Returns 1 if the TIV is transitioning (deploying or retracting), 0 otherwise."
E2Helper.Descriptions["tivWindSpeed(e:)"] = "Returns the wind speed at the TIV in MPH."
E2Helper.Descriptions["tivWindDirection(e:)"] = "Returns the wind direction vector at the TIV."
E2Helper.Descriptions["tivStress(e:)"] = "Returns the anchor wind stress (0.0 to 1.0) on the TIV."
E2Helper.Descriptions["tivSpikeCount(e:)"] = "Returns the total number of installed spikes on the TIV."
E2Helper.Descriptions["tivSpikeState(e:)"] = "Returns the overall spike state (idle, deploying, deployed, retracting, none)."
E2Helper.Descriptions["tivAnchorIntegrity(e:)"] = "Returns 1 if the TIV anchor integrity is holding, 0 if compromised."
E2Helper.Descriptions["tivIsLofted(e:)"] = "Returns 1 if the TIV is lofted in a tornado, 0 otherwise."
E2Helper.Descriptions["tivController(e:)"] = "Returns the Wire controller entity linked to the TIV."
E2Helper.Descriptions["tivDeploy(e:)"] = "Starts deployment of the TIV (initiates lowering, spikes, anchoring)."
E2Helper.Descriptions["tivRetract(e:)"] = "Starts retraction of the TIV (unanchors, retracts spikes, raises vehicle)."
E2Helper.Descriptions["tivToggle(e:)"] = "Toggles deploy/retract of the TIV."
E2Helper.Descriptions["tivEmergencyStop(e:)"] = "Aborts the active deploy sequence and recovers the TIV to idle."
E2Helper.Descriptions["tivReset(e:)"] = "Resets the TIV systems, clears failure states, and restores fresh spikes."
